repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.9.5
    hooks:
      - id: ruff
        args:
          - '--config'
          - '.ruff.toml'
          - '--fix'
          - '--unsafe-fixes'
      - id: ruff-format

  - repo: https://github.com/pdm-project/pdm
    rev: 2.22.3
    hooks:
      - id: pdm-export
        args:
          - '-o'
          - 'requirements.txt'
          - '--without-hashes'
          - '-G'
          - 'lint'
        files: ^pdm.lock$
      - id: pdm-lock-check
