version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "fsm_server"
    restart: always
    depends_on:
      - mysql
      - redis
    volumes:
      - ./backend:/fsm/backend
      - ./docker_conf.py:/fsm/backend/app/core/conf.py
      - fsm_static:/fsm/backend/app/static
    networks:
      - fsm_network
    command:
      - bash
      - -c
      - |
        wait-for-it -s mysql:3306 -s redis:6379 -t 300
        supervisord -c supervisor.conf

  mysql:
    image: mysql:8.0.29
    ports:
      - "3306:3306"
    container_name: "mysql"
    restart: always
    environment:
      MYSQL_DATABASE: fsm
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    volumes:
      - /var/lib/mysql
    networks:
      - fsm_network
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --lower_case_table_names=1

  redis:
    image: redis:6.2.7
    ports:
      - "6379:6379"
    container_name: "redis"
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /var/lib/redis
    networks:
      - fsm_network

  nginx:
    image: nginx
    ports:
      - "8000:80"
    container_name: "nginx"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - fsm_static:/www/fsm/backend/app/static
    networks:
      - fsm_network


networks:
  fsm_network:

volumes:
  fsm_static:
